train_file: data/rt_polarity/train.csv
valid_file: data/rt_polarity/valid.csv
test_file: data/rt_polarity/test.csv
embedding_source: pre-trained/embeddings/glove/glove.840B.300d.txt # char_one_hot
batch_size: 8
seq_len: # 300
epochs: 16
model: textrnn
seed: 313
